annotations: {}
csi:
  attacherReplicaCount: null
  kubeletRootDir: null
  provisionerReplicaCount: null
  resizerReplicaCount: null
  snapshotterReplicaCount: null
defaultSettings:
  allowRecurringJobWhileVolumeDetached: null
  allowVolumeCreationWithDegradedAvailability: null
  autoCleanupSystemGeneratedSnapshot: null
  autoDeletePodWhenVolumeDetachedUnexpectedly: null
  autoSalvage: null
  backingImageCleanupWaitInterval: null
  backingImageRecoveryWaitInterval: null
  backupCompressionMethod: null
  backupConcurrentLimit: null
  backupTarget: null
  backupTargetCredentialSecret: null
  backupstorePollInterval: null
  concurrentAutomaticEngineUpgradePerNodeLimit: null
  concurrentReplicaRebuildPerNodeLimit: null
  concurrentVolumeBackupRestorePerNodeLimit: null
  createDefaultDiskLabeledNodes: null
  defaultDataLocality: null
  defaultDataPath: null
  defaultLonghornStaticStorageClass: null
  defaultReplicaCount: null
  deletingConfirmationFlag: null
  disableRevisionCounter: null
  disableSchedulingOnCordonedNode: null
  engineReplicaTimeout: null
  failedBackupTTL: null
  fastReplicaRebuildEnabled: true
  guaranteedEngineManagerCPU: null
  guaranteedReplicaManagerCPU: null
  kubernetesClusterAutoscalerEnabled: null
  logLevel: null
  nodeDownPodDeletionPolicy: null
  nodeDrainPolicy: null
  offlineReplicaRebuilding: null
  orphanAutoDeletion: null
  priorityClass: null
  recurringFailedJobsHistoryLimit: null
  recurringSuccessfulJobsHistoryLimit: null
  removeSnapshotsDuringFilesystemTrim: null
  replicaAutoBalance: best-effort
  replicaFileSyncHttpClientTimeout: null
  replicaReplenishmentWaitInterval: null
  replicaSoftAntiAffinity: true
  replicaZoneSoftAntiAffinity: null
  restoreConcurrentLimit: null
  restoreVolumeRecurringJobs: null
  snapshotDataIntegrity: null
  snapshotDataIntegrityCronjob: null
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: null
  storageMinimalAvailablePercentage: null
  storageNetwork: null
  storageOverProvisioningPercentage: null
  supportBundleFailedHistoryLimit: null
  systemManagedComponentsNodeSelector: null
  systemManagedPodsImagePullPolicy: null
  taintToleration: null
  upgradeChecker: null
  v2DataEngine: null
  defaultNodeSelector:
    enable: false
enablePSP: false
global:
  cattle:

ingress:
  annotations: null
  enabled: false
  host: sslip.io
  ingressClassName: null
  path: /
  secrets: null
  secureBackends: false
  tls: false
  tlsSecret: longhorn.local-tls
longhornDriver:
  nodeSelector: {}
  priorityClass: null
  tolerations: []
longhornManager:
  log:
    format: plain
  nodeSelector: {}
  priorityClass: null
  serviceAnnotations: {}
  tolerations: []
longhornUI:
  nodeSelector: {}
  priorityClass: null
  replicas: 2
  tolerations: []
namespaceOverride: ''
networkPolicies:
  enabled: false
  type: k3s
persistence:
  backingImage:
    dataSourceParameters: null
    dataSourceType: null
    enable: false
    expectedChecksum: null
    name: null
  defaultClass: true
  defaultClassReplicaCount: 3
  defaultDataLocality: disabled
  defaultFsType: ext4
  defaultMkfsParams: ''
  defaultNodeSelector:
    enable: false
    selector: ''
  migratable: false
  reclaimPolicy: Delete
  recurringJobSelector:
    enable: false
    jobList: []
  removeSnapshotsDuringFilesystemTrim: ignored
privateRegistry:
  createSecret: null
  registryPasswd: null
  registrySecret: null
  registryUrl: null
  registryUser: null
service:
  manager:
    loadBalancerIP: ''
    loadBalancerSourceRanges: ''
    nodePort: ''
    type: ClusterIP
  ui:
    nodePort: null
    type: ClusterIP
serviceAccount:
  annotations: {}
longhorn:
  default_setting: true
