defaultNamespace: fleet-default
diff:
  comparePatches:
  - apiVersion: provisioning.cattle.io/v1
    kind: Cluster
    name: rke2-test-fleet
    namespace: fleet-default
    operations:
    - {"op":"remove", "path":"/spec/localClusterAuthEndpoint"}
  - apiVersion: provisioning.cattle.io/v1
    kind: Cluster
    name: rke2-test-fleet
    namespace: fleet-default
    operations:
    - {"op":"remove", "path":"/spec/rkeConfig/etcd/disableSnapshots"}
 